language: node_js #使用Node语言环境
node_js: stable #安装稳定版Node


# S: Build Lifecycle
install:
  - npm install

before_script:
  - export TZ='Asia/Shanghai' #设置时区
  - npm install -g gulp  #全局安装Gulp
  - chmod +x _travis.sh  #授权脚本执行权限

script:
  - hexo clean && hexo g #清除缓存并生成静态文件

after_script:
  - ./_travis.sh #执行部署脚本

# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/Shijf/shijf.github.io.git
   - CODING_REF: e.coding.net/shijf/shijf.coding.me.git
