language: node_js #使用Node语言环境
node_js: stable #安装稳定版Node


# S: Build Lifecycle
install:
  - npm install
  - hexo clean && hexo g

script:
  - pwd
after_script:
  - cd ./public
  - echo "blog.sharef.top" >> CNAME
  - git init
  - git config user.name "shijf"
  - git config user.email "shijf_private@163.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - rm "CNAME"
  - echo " <p>Hosted by <a href= \"https://pages.coding.me \" style=\"font-weight: bold \">Coding Pages</a></p> " >> index.html
  - git push --force --quiet "https://shijf:${CODING_TOKEN}@${CODING_REF}" master:master


# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/Shijf/shijf.github.io.git
   - CODING_REF: git.coding.net/shijf/shijf.coding.me.git
